apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  configuration.cfg: |-
    {{- .Values.configFileContent | nindent 4 }}